### ISSUE TITLE
Yaml Scanner Error during create

### ISSUE THREAD

**Issue by mondevert0815** [fhlab/UMIC-seq#1]
Hello, I'm working in a Linux environment with both anaconda3 and miniconda3 available for the create command. I would like to create the container provided in UMIC-seq.yml, but when I run 'conda env create -f UMIC-seq.yml' I get the following error (the caret is pointing to the colon in this string `&quot;version&quot;: `) :     

`ruamel_yaml.scanner.ScannerError: mapping values are not allowed here in "<unicode string>", line 91, column 65:
         ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ...`
                                                                       ^ 
It appears that the problematic block of code contains this same character pattern throughout, so I am not sure how to proceed. Do you have any ideas? Have you encountered this before?

Thank you!

**Comment by pauljannis** [comment]
Hi!
This seems to be an issue with the yml file when saved from github. 
Can you make sure to save it through the "raw" button? This solved the issue for me.

**Comment by mondevert0815** [comment]
Thank you for your help, I was able to create the environment.
