### ISSUE TITLE
Due to the lack of sequencing_summary.txt, the results have failed.

### ISSUE THREAD

**Issue by Seaxingzhou** [fhlab/UMIC-seq#2]
Hi pauljannis,
I'm stuck in using nanopolish index command because of taking too much time when I try to repeat your results using example_randomreads.fastq. I found that this step would be better if add  sequencing_summary.txt to index every cluster.fasta with fasta5 files. 
Could you provide sequencing_summary.txt for RAW_UMICseq_AmDH tar.gz?

I would truly appreciate your help.
Many thanks!

**Comment by pauljannis** [comment]
Hi Seaxingzhou, I realize this is probably too late but wanted to add the sequencing_summary.txt anyway in case someone else was looking for it. You can find it here now: https://www.dropbox.com/s/pyqszkisbrm0zp4/sequencing_summary.txt.gz?dl=1
