### ISSUE TITLE
Errors in UMIC-seq.py

### ISSUE THREAD

**Issue by mdomarhabib** [fhlab/UMIC-seq#3]
I am a complete beginner in programming, so I followed the instructions as it is to run this pipeline. So far, only the Extraction of UMI step worked. Clustering approximation and Full clustering gave: runtime errors and name errors. Could you kindly debug the program? Thank you.

**Comment by pauljannis** [comment]
Hi, could you please provide some more information, what exactly was the command you ran and what did the errors say specifically?

**Comment by mdomarhabib** [comment]
Hi, thank for getting back to me. So I did something different and now getting a different error. I decided to install the version of packages in the README file. Extraction of UMI was ok. But stuck at clustertest.

(UMIC-seq) omarhabib@Omars-MacBook-Pro nanopore % python UMIC-seq.py UMIextract --input myreadsLib1.fastq --probe probe.fa --umi_loc up --umi_len 14 --output ExtractedUMIs.fa
/Users/omarhabib/opt/anaconda3/envs/UMIC-seq/lib/python3.7/site-packages/skbio/util/_testing.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as pdt
36461 sequences analysed

UMIs extracted: 22828
Discarded: 37.39%:
Bad alignment: 13617
Incomplete UMI: 16
(UMIC-seq) omarhabib@Omars-MacBook-Pro nanopore % python UMIC-seq.py clustertest --input ExtractedUMIs.fa --steps 20 70 10  --output UMIclustertest 
/Users/omarhabib/opt/anaconda3/envs/UMIC-seq/lib/python3.7/site-packages/skbio/util/_testing.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as pdt
Starting threshold approximation (12 threads)
Threshold 20: Average similarity 14.25 and median size 2                
Traceback (most recent call last):
  File "UMIC-seq.py", line 335, in <module>
    threshold_approx(umis, sample_size, left, right, step, output_name)
  File "UMIC-seq.py", line 303, in threshold_approx
    _, _, read_labels, scores_lst_lst = simplesim_cluster(umis, thresh, max_clusters=ssize, save_scores=True)
  File "UMIC-seq.py", line 208, in simplesim_cluster
    assert len(sim_lst) >= 1,  'Threshold too high'
AssertionError: Threshold too high

**Comment by pauljannis** [comment]
I see you only extract UMIs of 14 bp. This means the highest alignment score you can get is 28, which is why you get an error 'Threshold too high'. I'll fix this with a nicer error message when I have a bit of time. For now this should be solved by estimating a suitable threshold in the range of something like --steps 10 25 5
